### ISSUE TITLE
SyntaxError: invalid syntax in featureExtraction.py

### ISSUE THREAD

**Issue by kvougas** [tyiannak/pyImageClassification#1]
Hello, 
I tried to run the code in featureExtraction.py and I get

File "featureExtraction.py", line 120
    print "{0:1f}".format(100.0 * float(i) / len(imageFilesList))
                 ^
SyntaxError: invalid syntax

What is the problem?

**Comment by shreyas3336** [comment]
You are using Python3 while the system is designed on Python2. I recommend you to use Python2 as some libraries such as "pickle" won't get installed on Python3.

**Comment by Das-AnupKumar** [comment]
Got an error while running "python featureExtraction.py -featuresDir sampledata/spectrograms2/music/" 
Traceback (most recent call last):
  File "featureExtraction.py", line 238, in <module>
    main(sys.argv)
  File "featureExtraction.py", line 220, in main
    (FM, Files, FeatureNames) = getFeaturesFromDir(argv[2])
  File "featureExtraction.py", line 128, in getFeaturesFromDir
    return (Features, imageFilesList, Names)
UnboundLocalError: local variable 'Names' referenced before assignment

**UnboundLocalError: local variable 'Names' referenced before assignment**
